In [1]:
from google.colab import files

uploaded = files.upload()

Saving student_performance_dataset.csv to student_performance_dataset.csv

In [10]:
import pandas as pd
df = pd.read_csv("student_performance_dataset.csv")
df.head(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
5,6,Female,4.2,78.2,5.7,High School,Yes,No,No,79.8,81.6,B
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6,69.6,D
7,8,Male,6.2,86.4,6.0,High School,Yes,Yes,No,78.4,88.0,B
8,9,Male,5.3,81.3,6.7,Bachelors,Yes,No,No,63.8,84.4,B
9,10,Female,2.8,86.8,5.1,Bachelors,Yes,Yes,No,57.7,74.3,C

In [11]:
df.tail(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
990,991,Female,2.5,81.4,6.5,NaN,Yes,No,No,81.8,81.9,B
991,992,Female,5.1,71.7,5.6,Bachelors,Yes,Yes,No,51.0,80.4,B
992,993,Female,2.6,80.9,7.4,High School,Yes,Yes,No,72.1,78.8,C
993,994,Female,6.2,87.6,5.9,PhD,Yes,No,No,75.4,92.7,A
994,995,Female,4.5,75.4,9.4,Bachelors,Yes,Yes,No,69.1,79.1,C
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [8]:
df.shape

(1000, 12)

In [12]:
df.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='object')

In [16]:
rows, columns=df.shape
rows

1000

In [17]:
rows, columns=df.shape
columns

12

In [18]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [19]:
df.describe(include='all')

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
count,1000.000000,1000,1000.000000,1000.000000,1000.000000,898,1000,1000,1000,1000.000000,1000.000000,1000
unique,NaN,2,NaN,NaN,NaN,4,2,2,2,NaN,NaN,5
top,NaN,Female,NaN,NaN,NaN,High School,Yes,Yes,No,NaN,NaN,B
freq,NaN,510,NaN,NaN,NaN,356,854,572,684,NaN,NaN,354
mean,500.500000,NaN,3.570700,85.092300,6.799500,NaN,NaN,NaN,NaN,69.740900,83.543500,NaN
std,288.819436,NaN,1.478559,9.270685,1.203527,NaN,NaN,NaN,NaN,12.613425,10.341333,NaN
min,1.000000,NaN,0.500000,54.800000,3.200000,NaN,NaN,NaN,NaN,31.300000,46.800000,NaN
25%,250.750000,NaN,2.600000,78.800000,5.900000,NaN,NaN,NaN,NaN,61.000000,76.075000,NaN
50%,500.500000,NaN,3.600000,85.200000,6.800000,NaN,NaN,NaN,NaN,69.600000,83.800000,NaN
75%,750.250000,NaN,4.500000,91.900000,7.600000,NaN,NaN,NaN,NaN,78.400000,91.525000,NaN
max,1000.000000,NaN,8.100000,100.000000,10.000000,NaN,NaN,NaN,NaN,100.000000,100.000000,NaN

In [20]:
df.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.dtypes

student_id                      int64
gender                         object
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education             object
internet_access                object
extracurricular_activities     object
part_time_job                  object
previous_grade                float64
final_exam_score              float64
final_grade                    object
dtype: object

In [23]:
df.sample(10)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
811,812,Male,4.3,85.2,4.5,Bachelors,Yes,Yes,No,74.9,88.4,B
298,299,Male,1.7,73.2,7.2,Masters,No,Yes,No,67.9,69.2,D
595,596,Female,4.1,71.2,8.3,PhD,Yes,No,No,46.8,80.4,B
52,53,Male,0.9,89.9,6.3,Masters,Yes,No,No,66.8,72.6,C
663,664,Female,5.6,86.6,8.2,Masters,Yes,Yes,Yes,81.9,99.7,A
260,261,Male,0.5,83.1,6.4,NaN,Yes,Yes,No,68.9,71.3,C
266,267,Female,3.1,86.9,7.4,Masters,Yes,Yes,Yes,88.5,81.6,B
175,176,Female,6.6,77.5,6.9,Bachelors,Yes,Yes,No,56.0,89.7,B
708,709,Female,4.6,95.4,5.8,Masters,Yes,Yes,No,58.8,98.3,A
670,671,Male,3.5,80.2,6.1,Bachelors,Yes,Yes,No,71.7,60.8,D